str=input('Введите значение точек А и В: ')
bak=str.replace('A', '')
bak=bak.replace('B', '')
bak=bak.replace('a', '')
bak=bak.replace('b', '')
bak=bak.replace('(', '')
bak=bak.replace(')', '')
points=bak.split(';')
a=points[0].split(',')
b=points[1].split(',')
a[0]=int(a[0])
a[1]=int(a[1])
b[0]=int(b[0])
b[1]=int(b[1])
l=((b[0]-a[0])**2+(b[1]-a[1])**2)**0.5
# print(a[0], a[1], '    ', b[0],b[1])
print(round(l,2))